repos:
  - repo: local
    hooks:
      - id: ktlint-format
        name: ktlint format
        entry: ./gradlew ktlintFormat
        language: system
        files: \.kt$
        pass_filenames: false
      
      - id: ktlint-check
        name: ktlint check
        entry: ./gradlew ktlintCheck
        language: system
        files: \.kt$
        pass_filenames: false
      
      - id: detekt
        name: detekt
        entry: ./gradlew detekt
        language: system
        files: \.kt$
        pass_filenames: false
        
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: check-yaml