build:
  maxIssues: -1

style:
  active: true
  UnusedImports:
    active: true
  ForbiddenMethodCall:
    active: true
  MagicNumber:
    active: false
  ForbiddenComment:
    active: false
  MaxLineLength:
    active: true
    excludeRawStrings: true

exceptions:
  active: true
  PrintStackTrace:
    active: true
  TooGenericExceptionCaught: # TODO
    active: false

potential-bugs:
  active: true

naming:
  active: true
  FunctionNaming:
    active: true
    excludes: ['**/test/**', '**/androidTest/**', '**/commonTest/**', '**/jvmTest/**', '**/jsTest/**', '**/iosTest/**']
    functionPattern: '[a-z][a-zA-Z0-9]*'
    excludeClassPattern: '$^'
    ignoreAnnotated: ['Composable']

complexity:
  active: true
  LongMethod:
    active: false
  LongParameterList:
    active: false
  CyclomaticComplexMethod:
    active: false
