name: Build Android App

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: false
        load: true
        tags: translator-app:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
    
    - name: Run build in container
      run: |
        docker run --name build-container translator-app:latest
          -v ${{ github.workspace }}/app/src:/workspace/app/src \
          translator-app:latest
    
    - name: Copy APK files from container
      run: |
        docker cp build-container:/workspace/app/build/outputs ./app/build/
        docker rm build-container
    
    - name: Upload APK artifacts
      uses: actions/upload-artifact@v4
      with:
        name: apk-files
        path: app/build/outputs/apk/**/*.apk
        retention-days: 30
