name: Build Android App

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: false
        tags: translator-app:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
    
    - name: Run build in container
      run: |
        docker run --rm \
          -v ${{ github.workspace }}/app:/workspace/app \
          translator-app:latest
    
    - name: Upload APK artifacts
      uses: actions/upload-artifact@v4
      with:
        name: apk-files
        path: app/build/outputs/apk/**/*.apk
        retention-days: 30
